trigger:
  branches:
    include:
    - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- task: TfxInstaller@3
  inputs:
    version: 'v0.12.x'

- task: Npm@1
  displayName: 'NPM: Install Extension Dependencies'
  inputs:
    workingDir: .
    verbose: false

- task: Npm@1
  displayName: 'NPM: Build Extension'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'NPM: Install Task Dependencies'
  inputs:
    workingDir: tasks/generate-test-report
    verbose: false

- task: PackageAzureDevOpsExtension@3
  displayName: 'TFX: Package Extension'
  inputs:
    rootFolder: .
    publisherId: dattu
    extensionName: 'Test Report'
    extensionVisibility: public
    extensionPricing: free
    patternManifest: 'azure-devops-extension.json'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

- task: PackageAzureDevOpsExtension@3
  displayName: 'TFX: Package Extension Dev'
  inputs:
    rootFolder: .
    publisherId: dattu
    extensionId: 'azure-pipelines-test-report'
    extensionTag: dev
    extensionName: 'Test Report Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    updateTasksVersion: true
    extensionVisibility: private
    extensionPricing: free
    patternManifest: 'azure-devops-extension.json'
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: PublishAzureDevOpsExtension@3
  displayName: 'TFX: Publish Extension Dev'
  inputs:
    connectedServiceName: Marketplace
    rootFolder: .
    publisherId: dattu
    extensionId: 'azure-pipelines-test-report'
    extensionTag: dev
    extensionName: 'Test Report Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    extensionVisibility: private
    extensionPricing: free
    patternManifest: 'azure-devops-extension.json'
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: ShareAzureDevOpsExtension@3
  displayName: 'TFX: Share Extension'
  inputs:
    connectedServiceName: Marketplace
    method: vsix
    vsixFile: '**.vsix'
    accounts: 'dattu-dev'
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

